language: php
php:
- 7.1
- 7.2
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- WP_VERSION=4.9.8
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
install:
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh exex_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: uCBtfKoOS/kFsjUadYPTeyP9FXbAneXVH8IxP9Yt0cFxy2PuQv49jaH49icCW1kMgOnBIwD2Vg8RF8kwN8kwotYmGbTKX0HUu1TiRut8jZF7pNTjcMkigjE5Gy/42LfsHRgIKYWShnL+FUVz64l8EcVYAk04Pi4ss/AKCKutniBO9Q5Tp7pidOaUB4GHA1NOFtLv+FkOVsNVYhE9WyC431X816lBbRL+4wY6aXOClA9bW4eWa/9Ui6+eC6O2reHvtsXqWsstgS2ADYO6NjgURNfVrhvbeKMQRRCFzUaI5+MjyH7U71pm7X3mzO+PyKPyxk3XeGQdDrtevoGUs67iVTdErv5rjKKYOmynuq7M7sPkyKt3qsfVegk4nNzmLMoaHaw4Bs4cxYmoVieLiTLOVbpwQPf/PUY26UdgjLCLyLSD0ZItAKXjkQ3BTCvqFAcacK1dllknXEPU/rZJ76SDrZhqltvViqY/zqxQ5MADwNKAajanOyd4dgc4qbTB5W5MD90jDqKy3zGamXwgv+UwywJxfwFzPHBF6r8iqq9o+2Zvj6CFQGWVfzfA4COGxGamGENHmqdkzgqNSLYVMSW2nOOhu/MUMaGOEp+u70k2TuG9Dk5suhNzR7zBFct3s3/D9YtAOd32zfRGVXlwj0F/36v1Q2KPOdhiv1lPGgns2jg=
  file: excel-export-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/excel-export
    branch: dev
